### ISSUE TITLE
Can we use Octave instead of Matlab to run the program?

### ISSUE THREAD

**Issue by xanhho** [js05212/CDL#2]
Hi, 
Can I use Octave instead of Matlab?
If yes, Can I reproduce the result when using Octave?

Thank you very much!

**Comment by js05212** [comment]
I am not sure whether Octave have the same gpuArray support (I guess not). If not, you can comment out the all gpuArray lines and technically the results can be reproduced. But it may be a lot slower without GPU support.

**Comment by xanhho** [comment]
Hi,
Thank you for your reply!
Can you supply the table score of CDL model when using recall@M to evaluate the results?
After finished training CDL model, to predict the ratings, we just multiply the matrix V and transpose of matrix U or are you use any other process to predict the ratings?

Thank you very much!
