### ISSUE TITLE
error while import data

### ISSUE THREAD

**Issue by PatelAxita** [js05212/CDL#5]
ImportError                               Traceback (most recent call last)
<ipython-input-2-8733d28f0d92> in <module>()
      2 import numpy as np
      3 import logging
----> 4 import data
      5 from math import sqrt
      6 from autoencoder import AutoEncoderModel

ImportError: No module named data

**Comment by js05212** [comment]
Hi, 

Have you include the file https://github.com/js05212/MXNet-for-CDL/blob/master/data.py in the folder?

**Comment by PatelAxita** [comment]
Sir, i checked that file is in my folder and now i'm getting this errors
Traceback (most recent call last):
  File "cdl.py", line 14, in <module>
    import data
File "/home/axita/Downloads/CDL/MXNet-for-CDL/data.py", line 2, in <module>
    from mult import read_mult
  File "/home/axita/Downloads/CDL/MXNet-for-CDL/mult.py", line 8
    strs = line.strip().split(' ')[1:]
       ^
SyntaxError: invalid syntax

when i run cdl.py
