### ISSUE TITLE
Reproduce Error

### ISSUE THREAD

**Issue by jieWANGforwork** [js05212/CDL#6]
Hi,
I have faced this problem for several days, and never solved. Could you please tell me the matlab version you used, If you can,  please give me a hint to solve this problem.
Error using gpuArray/hTimesTranspose
Call to sgemm in CUBLAS failed with error status: CUBLAS_STATUS_EXECUTION_FAILED.

Error in cdl (line 212)
            h0d{l} = bsxfun(@plus, h0d{l+1} * S.W{l}',  S.biases{l}');

Error in cdl_worker (line 255)
S = cdl (S, X, X_valid, X_ori, 0.1,my,perm_idx);

Error in cdl_main (line 16)
cdl_worker(para_gpuDevice,para_layers,para_blayers,...
Thanks.

**Comment by js05212** [comment]
Hi,

If I remember correctly the version should be around 2012b.

**Comment by jieWANGforwork** [comment]
Thanks, I'll try.
