### ISSUE TITLE
A question about P

### ISSUE THREAD

**Issue by eminemichael** [js05212/CDL#9]
When P=1, how is feature vector of this user trained, won't it be unchanged?

**Comment by js05212** [comment]
Hi,

In the extreme case of P = 1, if two users happen to rate the same item as positive, their latent vectors will be the same, and they will equal to the vector of the rated item v_j. v_j will change as the deep learning part of the model is trained and changes.

**Comment by eminemichael** [comment]
Thanks for your reply~
